filter out datetime from facts config
ansible-collections/community.routeros pull request #21
Opened 2021-03-23 14:21 UTC by qaxi

##### SUMMARY

Every time 'community.routeros.facts' subset 'config' returns data it's status is 'not changed' in persptective of device it is OK, but ...
Returned data are different on every run of 'community.routeros.facts' even configuration on device is not changed

Fixes #20 part 1.

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME

'community.routeros.facts' subset 'config'

##### ADDITIONAL INFORMATION

```BEFORE
# mar/22/2021 18:23:30 by RouterOS 6.40.3
# software id = 2TZZ-SFZA
#
# model = RouterBOARD 750G r3
# serial number = 6F3806FD9931
/interface ethernet
set [ find default-name=ether1 ] advertise=\
    10M-half,10M-full,100M-half,100M-full,1000M-half,1000M-full arp=enabled \
```
```AFTER
# RouterOS 6.40.3
# software id = 2TZZ-SFZA
#
# model = RouterBOARD 750G r3
# serial number = 6F3806FD9931
/interface ethernet
set [ find default-name=ether1 ] advertise=\
    10M-half,10M-full,100M-half,100M-full,1000M-half,1000M-full arp=enabled \

```

2021-03-23 14:31 UTC, heuels commented
@qaxi, thanks for opening this PR! Could you also add a unit test for this change and a changelog fragment?

2021-03-23 14:39 UTC, felixfontein requested changes
This is a breaking change. It need to be explicitly enabled by a module option.

(Docs on changelog fragments can be found here: https://docs.ansible.com/ansible/devel/community/development_process.html#changelogs-how-to)

2021-03-23 14:56 UTC, closed without merging

2021-03-23 14:58 UTC, qaxi commented
> This is a breaking change. It need to be explicitly enabled by a module option.

understand, will work on it, it needs more than such simple change

2021-03-23 15:25 UTC, qaxi commented
Just question for @felixfontein or @heuels 

what is better solution:

add new return value _ansible_net_config_idempotent_

```
    # config
    ansible_net_config:
      description: The current active config from the device
      returned: when config is configured
      type: str

    ansible_net_config_idempotent:
      description: The current active config from the device in minimal idempotent form
      returned: when config is configured
      type: str
```

or add option _idempotent_config_ with default _false_

```
option:
  idempotent_config:
    description:
      - When set C(true), config data will contain nonverbose config and will
        be idempotent between subsequent runs of facts module. 
    required: false
    default: false
```

2021-03-24 06:31 UTC, felixfontein commented
The problem with putting 'idempotent' in there is that it really needs to be idempotent. So if RouterOS ever starts adding something non-deterministic somewhere, we have to rush and filter it out / fix it somehow. That's potentially a very complex and complicated undertaking, and I'm not sure if we should commit on really doing it that way. Also you already mentioned another idempotency problem in #20, which would need to be covered as well for this to be idempotent, like the random MAC address you've mentioned, which would actually require us to parse and understand the config. I think that's not something that this module should do.

I see two options:
1. Have another module for retrieving only the config, and which tries to make it idempotent - would be more complex, or do a lot more calls, to try to eliminate all randomness.
2. Move that to a jinja2 filter plugin, which processes a config as a string. (That couldn't do multiple requests, so it would have to understand the config to a certain degree.)

2021-03-24 08:42 UTC, qaxi commented
There are two things

The date
- it is in _/export_ and _/export verbose_ output too 
- it is easy to filter it out
IMHO - it could be filtered from both outputs, but it is OK let current config mode untouched

The MAC randomness
- it is there because _/export verbose_ does show state of _unconfigured_ services with auto-generated parameters (https://wiki.mikrotik.com/wiki/Manual:Interface/OVPN mac-address ...)
- if you configure something _/export_ will show you just and only what you wrote ... so it is 'idempotent'

I understand your worries, so lets remove _idempotent_ and replace it with _verbose_ .

In this case I would prefer the second form - option

```
    # config
    ansible_net_config:
      description: The current active config from the device
      returned: when config is configured
      type: str

    ansible_net_config_nonverbose:
      description: The current active config from the device in minimal form
      returned: when config is configured
      type: str
```

or add option _verbose_config_ with default _true_

```
option:
  verbose_config:
    description:
      - When set C(false), config data will contain nonverbose config 
    required: false
    default: true
```

2021-03-24 16:53 UTC, felixfontein commented
Ok, if `/export` is fine, having `..._config_nonverbose` sounds good to me. It definitely should come with `version_added: 1.2.0` though (and a changelog fragment :) ). Do we want to remove the date (resp. first line) always, or make that configurable? Both would be fine for me. @heuels any preference?

2021-03-24 17:54 UTC, heuels commented
@felixfontein, I'd remove it unconditionally. If you want current date, there are more effective ways of getting it than `routeros_config`, right? 🙂

2021-03-24 20:57 UTC, felixfontein commented
@heuels good point! If someone wants the exact output of `/export`, they can just use the `community.routeros.command` module :)