Change ip vrf for router OS v7
ansible-collections/community.routeros pull request #259
Opened 2024-02-06 10:28 UTC by liquorice-head

##### SUMMARY

##### ISSUE TYPE

- Bugfix Pull Request
- Docs Pull Request
- Feature Pull Request
- New Module Pull Request

##### COMPONENT NAME

##### ADDITIONAL INFORMATION

```paste below
In router OS 7, the path to vrf and the fields used have changed
```

2024-02-06 10:46 UTC, derdeagle requested changes

2024-02-06 11:19 UTC, liquorice-head commented on plugins/module_utils/_api_data.py
> +                'numbers': KeyInfo(),
<img width="813" alt="Screenshot 2024-02-06 at 15 00 26" src="https://github.com/ansible-collections/community.routeros/assets/40302350/7a49e8cd-5000-48de-aae9-ba7c94fd2e4f">
in ip vrf set there is such an entry

2024-02-06 11:22 UTC, felixfontein reviewed
Thanks for your contribution! Below a first comment from my side. Please note that you need to add a [changelog fragment](https://docs.ansible.com/ansible/devel/community/collection_development_process.html#creating-a-changelog-fragment), but it might be easier to wait a bit until it's clear how this PR will look before adding it :)

2024-02-06 11:22 UTC, felixfontein commented on plugins/module_utils/_api_data.py
> +    ('ip', 'vrf'): APIData(
This breaks all users of older RouterOS versions. Better add a copy of this path for RouterOS 7 with the new path, and keep the old one for previous versions.

2024-02-06 11:25 UTC, liquorice-head commented on plugins/module_utils/_api_data.py
> +                'numbers': KeyInfo(),
Thanks for the explanation. I've made the change.

2024-02-06 13:00 UTC, ialshaev commented
@felixfontein is it possible to have both versions for vrf path? So we can decide what path to chose depending on RouterOS version.
Thank you in advance!

2024-02-13 06:35 UTC, liquorice-head commented
Added versioning. Pls review

2024-02-13 20:46 UTC, felixfontein reviewed
Looks almost good now, see my comment below! Please don't forget the [changelog fragment](https://docs.ansible.com/ansible/devel/community/collection_development_process.html#creating-a-changelog-fragment) :)

2024-02-13 20:46 UTC, felixfontein commented on plugins/modules/api_info.py
> +        - ip vrf
This needs to be moved to the right position (lexicographically sorted), i.e. after `ip upnp interfaces`. Same in the other file.

2024-02-14 08:40 UTC, liquorice-head commented
Done. Please review

2024-02-14 21:52 UTC, felixfontein commented on changelogs/fragments/259-add-routeros7-support-for-ip-vrf.yml
> +  - api_modify, api_info - add support for the ``ip vrf`` path in RouterOS 7  (https://github.com/ansible-collections/community.routeros/pull/259)
```suggestion
  - api_modify, api_info - add support for the ``ip vrf`` path in RouterOS 7 and support new primary keys ``routing-mark`` for RouterOS 7 (https://github.com/ansible-collections/community.routeros/pull/259)
```

2024-02-14 21:52 UTC, felixfontein commented on changelogs/fragments/259-add-routeros7-support-for-ip-vrf.yml
> +  - api_data - add support for the ``ip vrf`` path in RouterOS 7 and add support new primary_keys ``routing-mark`` for RouterOS 7 (https://github.com/ansible-collections/community.routeros/pull/259)
```suggestion
```

2024-02-16 17:53 UTC, derdeagle approved these changes
Looks good to me.

2024-02-17 11:30 UTC, felixfontein commented on changelogs/fragments/259-add-routeros7-support-for-ip-vrf.yml
> +  - api_modify, api_info - add support for the ``ip vrf`` path in RouterOS 7  (https://github.com/ansible-collections/community.routeros/pull/259)
I copied that part over from the other part that was removed. If it's wrong, I don't mind not having this here :)

2024-02-17 21:49 UTC, merged

2024-02-17 21:49 UTC, felixfontein commented
@liquorice-head thanks for implementing this!
@derdeagle thanks for reviewing this!

2024-02-17 21:50 UTC, derdeagle commented
Always a pleasure ;)